[tool.black]
line-length = 100
exclude = '''
(
  /(
    | .eggs
    |\.git
    |\.hg
    |\.mypy_cache
    |\.nox
    |\.tox
    |\.venv
    |\.svn
    |_build
    |buck-out
    |build
    |dist
  )/
)
'''
